serial_no: 18581551
cam_name: "ximea_floka_r"
yaml_url: "package://ximea_camera/calibrations/camera_calibration_floka_ximea_r.yaml"
use_cam_timestamp: true
image_data_format: "XI_RAW8"
allocated_bandwidth: 0.95
