serial_no: 0
cam_name: "camera_first_on_bus"
yaml_url: "package://mcptam/calibrations/camera1.yaml"
exposure_time: 30000
rect_left: 0
rect_top: 0
rect_height: 1080
rect_width: 2040
image_data_format: "XI_RGB24"
